FROM golang:1.26.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -o /bootstrap \
    ./cmd/lambda

FROM gcr.io/distroless/static-debian12

WORKDIR /

COPY --from=builder /bootstrap /bootstrap

EXPOSE 8080

ENTRYPOINT ["/bootstrap"]
