services:
  ministack:
    image: ministackorg/ministack
    container_name: ministack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,kinesis
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  recommendation-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      GIN_MODE: "debug"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      DYNAMODB_ENDPOINT: "http://ministack:4566"
      KINESIS_ENDPOINT: "http://ministack:4566"
      USE_LOCAL_AWS: "true"
    depends_on:
      - ministack